version: "3"
services:
  frontend:
    container_name: erp-frontend
    build: ./webapp/
    ports:
      - 4000:4000
    volumes:
      - ./webapp/src:/app/src
    restart: always
    depends_on:
      - backend
  backend:
    container_name: erp-backend
    build: ./server/
    ports:
      - 3333:3333
    volumes:
      - ./server/src:/app/src
    restart: always
    env_file:
      - ./server/.env
    depends_on:
      - database
  database:
    container_name: erp-database
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ./server/data:/var/lib/mysql
    restart: always
    env_file:
      - ./server/.env
  redis:
    image: "redis:alpine"
    restart: always
