version: "3"
services:
  backend:
    container_name: erp-backend
    build: .
    ports:
      - 3333:3333
    volumes:
      - ./src:/app/src
    restart: always
    env_file:
      - ./.env
    depends_on:
      - database
  database:
    container_name: erp-database
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    restart: always
    env_file:
      - ./.env
